

okhv = "OKH-LOSHv1.0"
name = "nimble"
repo = "https://gitlab.com/Wakoma/nimble"
version = "0.1.0"
license = "CERN-OHL-S-2.0"
licensor = "Eric Nitschke <eric@wakoma.co>"
organization = "Wakoma"
readme = "README.md"
image = "res/assets/media/img/12.jpg"
documentation-language = "en-US"
#technology-readiness-level = "OTRL-5"
#documentation-readiness-level = "ODRL-4"
function = "An open source, rapidly deployable, wireless mesh network."
#cpc-patent-class = "D03D 35/00"
#tsdc = "MEC"
#bom = "sBoM.csv"
#manufacturing-instructions = "doc/assembly/main.md"
#user-manual = "doc/usr/main.md"
