#!/bin/bash

if [ $# = 1 ]
then
    filename=$1
    filename_output="${filename:0:-4}.pdf"
    inkscape --export-pdf=$filename_output --export-pdf-version=1.4 $filename 
else
    echo "USAGE: $(basename $0) <file.svg>"
fi
