# SPDX-FileCopyrightText: 2023 Robin Vobruba <hoijui.quaero@gmail.com>
#
# SPDX-License-Identifier: Unlicense

name: check

on:
  push:
    branches: [ master, main, fccitest ]

jobs:
  gen_freecad_stls:
    name: Generate STLs
    runs-on: ubuntu-latest
    container: amrit3701/freecad-cli:latest
    steps:
      - name: "Check out the repo"
        uses: actions/checkout@v3

      - name: Generate STLs
        run: |
          pwd
          ls
          mkdir gen/mech/freecad
          for i in src/mech/freecad/*.FCStd; do
            python3 src/mech/freecad/freecad_to_stl.py $i gen/mech/freecad/`basename $i`.stl
          done
          ls gen/mech/freecad/
      - name: Upload STLs
        uses: actions/upload-artifact@v3
        with:
          name: freecad-stls
          path: gen/mech/freecad/*
