name: Lint

on: [push]

jobs:
  python-lint:
    
    name: lint
    runs-on: ubuntu-latest
    steps:
      - name: "Check out the repo"
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Fix checkout ownership
        run: |
          # HACK Workaround for bug:
          # https://github.com/actions/runner/issues/2033
          mkdir -p /home/runner/work/_temp/_github_home
          printf "[safe]\n\tdirectory = /github/workspace" \
            > /home/runner/work/_temp/_github_home/.gitconfig

      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install nimble packages and dev tools
        run: |
          pip install .[dev]

      - name: Lint python
        run: |
          ./lint_test.py -t py

  cadquery-lint:
    
    name: lint
    runs-on: ubuntu-latest
    steps:
      - name: "Check out the repo"
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Fix checkout ownership
        run: |
          # HACK Workaround for bug:
          # https://github.com/actions/runner/issues/2033
          mkdir -p /home/runner/work/_temp/_github_home
          printf "[safe]\n\tdirectory = /github/workspace" \
            > /home/runner/work/_temp/_github_home/.gitconfig

      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install nimble packages and dev tools
        run: |
          pip install .[dev]
      - name: Lint CadQuery scripts
        run: |
          ./lint_test.py -t cad-query
