name: Test

on: [push]

jobs:
  test:
    name: Test
    runs-on: ubuntu-24.04
    steps:
      - name: "Check out the repo"
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Fix checkout ownership
        run: |
          # HACK Workaround for bug:
          # https://github.com/actions/runner/issues/2033
          mkdir -p /home/runner/work/_temp/_github_home
          printf "[safe]\n\tdirectory = /github/workspace" \
            > /home/runner/work/_temp/_github_home/.gitconfig

      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install system dependencies
        run: |
          sudo apt update && sudo apt install -y libgl1 libglx-mesa0 libosmesa6

      - name: Install nimble packages and dev tools
        run: |
          pip install -e .[dev]

      - name: Run tests
        run: |
          pytest
