name: Test

on: [push]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: "Check out the repo"
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Fix checkout ownership
        run: |
          # HACK Workaround for bug:
          # https://github.com/actions/runner/issues/2033
          mkdir -p /home/runner/work/_temp/_github_home
          printf "[safe]\n\tdirectory = /github/workspace" \
            > /home/runner/work/_temp/_github_home/.gitconfig

      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install system dependencies
        run: |
          sudo apt update && sudo apt install -y libgl1 libglx-mesa0

      - name: Install nimble packages and dev tools
        run: |
          pip install -e .[dev]
          pip list

      - name: Run tests
        uses: coactions/setup-xvfb@v1
        with:
          run: pytest

      - name: Upload rendered images as artifacts for inspection
        uses: actions/upload-artifact@v4
        with:
          name: rendered-images
          path: renders/*.png
